name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create token.json
        run: python .github/workflows/use_secret.py

      - name: Show token.json with secret
        run: cat ./token.json

      - name: Run tests
        env:
          PYTHONPATH: /home/runner/work/GoogleCloudStorage/GoogleCloudStorage
        run: |
          python .github/workflows/auto_testing.py

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: .github/workflows/test-reports/results.log
